package br.com.flaviomarcilio.model.enums;

public enum TipoMovimentacao {
    BONIFICACAO_EM_ATIVOS,
    DESDOBRO,
    DIREITOS_DE_SUBSCRICAO_NAO_EXERCIDO,
    DIREITO_DE_SUBSCRICAO,
    DIVIDENDO,
    DIVIDENDO_TRANSFERIDO,
    JUROS_SOBRE_CAPITAL_PROPRIO,
    JUROS_SOBRE_CAPITAL_PROPRIO_TRANSFERIDO,
    RENDIMENTO,
    TRANSFERENCIA,
    TRANSFERENCIA_LIQUIDACAO

}
